//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.08 at 10:21:15 PM EST 
//


package info.openlyrics.namespace._2009.song;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the info.openlyrics.namespace._2009.song package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LinesTypeBr_QNAME = new QName("", "br");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: info.openlyrics.namespace._2009.song
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LinesType }
     * 
     */
    public LinesType createLinesType() {
        return new LinesType();
    }

    /**
     * Create an instance of {@link Song }
     * 
     */
    public Song createSong() {
        return new Song();
    }

    /**
     * Create an instance of {@link PropertiesType }
     * 
     */
    public PropertiesType createPropertiesType() {
        return new PropertiesType();
    }

    /**
     * Create an instance of {@link LyricsType }
     * 
     */
    public LyricsType createLyricsType() {
        return new LyricsType();
    }

    /**
     * Create an instance of {@link VerseType }
     * 
     */
    public VerseType createVerseType() {
        return new VerseType();
    }

    /**
     * Create an instance of {@link AuthorsType }
     * 
     */
    public AuthorsType createAuthorsType() {
        return new AuthorsType();
    }

    /**
     * Create an instance of {@link TitlesType }
     * 
     */
    public TitlesType createTitlesType() {
        return new TitlesType();
    }

    /**
     * Create an instance of {@link LinesType.Br }
     * 
     */
    public LinesType.Br createLinesTypeBr() {
        return new LinesType.Br();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinesType.Br }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "br", scope = LinesType.class)
    public JAXBElement<LinesType.Br> createLinesTypeBr(LinesType.Br value) {
        return new JAXBElement<LinesType.Br>(_LinesTypeBr_QNAME, LinesType.Br.class, LinesType.class, value);
    }

}
