//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.08 at 10:21:15 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://openlyrics.info/namespace/2009/song", elementFormDefault=javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package info.openlyrics.namespace._2009.song;
